# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerRunTable extends _ModuleTable

signal inserted(row: RunnerRun)
signal updated(old_row: RunnerRun, new_row: RunnerRun)
signal deleted(row: RunnerRun)

var id: RunnerRunIdUniqueIndex
var party_id: RunnerRunPartyIdBTreeIndex
var server: RunnerRunServerBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"run"
	id = RunnerRunIdUniqueIndex.new(p_local_db)
	party_id = RunnerRunPartyIdBTreeIndex.new(p_local_db)
	server = RunnerRunServerBTreeIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[RunnerRun]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[RunnerRun] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[RunnerRun]:
	var rows: Array = super(predicate)
	var typed_array: Array[RunnerRun] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> RunnerRun:
	return super(predicate) as RunnerRun

func find_by(field: StringName, value: Variant) -> Array[RunnerRun]:
	var rows: Array = super(field, value)
	var typed_array: Array[RunnerRun] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> RunnerRun:
	return super(field, value) as RunnerRun

func find_by_id(value: int) -> Array[RunnerRun]:
	var row: RunnerRun = id.find(value)
	var result: Array[RunnerRun] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> RunnerRun:
	return id.find(value)

func find_by_party_id(value: int) -> Array[RunnerRun]:
	return party_id.filter(value)

func first_by_party_id(value: int) -> RunnerRun:
	return party_id._first_row(value) as RunnerRun

func find_by_zone(value: String) -> Array[RunnerRun]:
	return find_by(&"zone", value)

func first_by_zone(value: String) -> RunnerRun:
	return first_by(&"zone", value)

func find_by_seed(value: int) -> Array[RunnerRun]:
	return find_by(&"seed", value)

func first_by_seed(value: int) -> RunnerRun:
	return first_by(&"seed", value)

func find_by_server(value: PackedByteArray) -> Array[RunnerRun]:
	return server.filter(value)

func first_by_server(value: PackedByteArray) -> RunnerRun:
	return server._first_row(value) as RunnerRun

func find_by_address(value: String) -> Array[RunnerRun]:
	return find_by(&"address", value)

func first_by_address(value: String) -> RunnerRun:
	return first_by(&"address", value)

func find_by_state(value: String) -> Array[RunnerRun]:
	return find_by(&"state", value)

func first_by_state(value: String) -> RunnerRun:
	return first_by(&"state", value)

func find_by_created_at(value: int) -> Array[RunnerRun]:
	return find_by(&"created_at", value)

func first_by_created_at(value: int) -> RunnerRun:
	return first_by(&"created_at", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as RunnerRun)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as RunnerRun, new_row as RunnerRun)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as RunnerRun)
