# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerChatMessageTable extends _ModuleTable

signal inserted(row: RunnerChatMessage)
signal updated(old_row: RunnerChatMessage, new_row: RunnerChatMessage)
signal deleted(row: RunnerChatMessage)

var id: RunnerChatMessageIdUniqueIndex
var channel: RunnerChatMessageChannelBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"chat_message"
	id = RunnerChatMessageIdUniqueIndex.new(p_local_db)
	channel = RunnerChatMessageChannelBTreeIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[RunnerChatMessage]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[RunnerChatMessage] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[RunnerChatMessage]:
	var rows: Array = super(predicate)
	var typed_array: Array[RunnerChatMessage] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> RunnerChatMessage:
	return super(predicate) as RunnerChatMessage

func find_by(field: StringName, value: Variant) -> Array[RunnerChatMessage]:
	var rows: Array = super(field, value)
	var typed_array: Array[RunnerChatMessage] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> RunnerChatMessage:
	return super(field, value) as RunnerChatMessage

func find_by_id(value: int) -> Array[RunnerChatMessage]:
	var row: RunnerChatMessage = id.find(value)
	var result: Array[RunnerChatMessage] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> RunnerChatMessage:
	return id.find(value)

func find_by_channel(value: String) -> Array[RunnerChatMessage]:
	return channel.filter(value)

func first_by_channel(value: String) -> RunnerChatMessage:
	return channel._first_row(value) as RunnerChatMessage

func find_by_sender(value: PackedByteArray) -> Array[RunnerChatMessage]:
	return find_by(&"sender", value)

func first_by_sender(value: PackedByteArray) -> RunnerChatMessage:
	return first_by(&"sender", value)

func find_by_sender_name(value: String) -> Array[RunnerChatMessage]:
	return find_by(&"sender_name", value)

func first_by_sender_name(value: String) -> RunnerChatMessage:
	return first_by(&"sender_name", value)

func find_by_text(value: String) -> Array[RunnerChatMessage]:
	return find_by(&"text", value)

func first_by_text(value: String) -> RunnerChatMessage:
	return first_by(&"text", value)

func find_by_sent_at(value: int) -> Array[RunnerChatMessage]:
	return find_by(&"sent_at", value)

func first_by_sent_at(value: int) -> RunnerChatMessage:
	return first_by(&"sent_at", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as RunnerChatMessage)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as RunnerChatMessage, new_row as RunnerChatMessage)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as RunnerChatMessage)
