# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerRunMemberTable extends _ModuleTable

signal inserted(row: RunnerRunMember)
signal updated(old_row: RunnerRunMember, new_row: RunnerRunMember)
signal deleted(row: RunnerRunMember)

var id: RunnerRunMemberIdUniqueIndex
var identity: RunnerRunMemberIdentityBTreeIndex
var run_id: RunnerRunMemberRunIdBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"run_member"
	id = RunnerRunMemberIdUniqueIndex.new(p_local_db)
	identity = RunnerRunMemberIdentityBTreeIndex.new(p_local_db)
	run_id = RunnerRunMemberRunIdBTreeIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[RunnerRunMember]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[RunnerRunMember] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[RunnerRunMember]:
	var rows: Array = super(predicate)
	var typed_array: Array[RunnerRunMember] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> RunnerRunMember:
	return super(predicate) as RunnerRunMember

func find_by(field: StringName, value: Variant) -> Array[RunnerRunMember]:
	var rows: Array = super(field, value)
	var typed_array: Array[RunnerRunMember] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> RunnerRunMember:
	return super(field, value) as RunnerRunMember

func find_by_id(value: int) -> Array[RunnerRunMember]:
	var row: RunnerRunMember = id.find(value)
	var result: Array[RunnerRunMember] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> RunnerRunMember:
	return id.find(value)

func find_by_run_id(value: int) -> Array[RunnerRunMember]:
	return run_id.filter(value)

func first_by_run_id(value: int) -> RunnerRunMember:
	return run_id._first_row(value) as RunnerRunMember

func find_by_identity(value: PackedByteArray) -> Array[RunnerRunMember]:
	return identity.filter(value)

func first_by_identity(value: PackedByteArray) -> RunnerRunMember:
	return identity._first_row(value) as RunnerRunMember

func find_by_name(value: String) -> Array[RunnerRunMember]:
	return find_by(&"name", value)

func first_by_name(value: String) -> RunnerRunMember:
	return first_by(&"name", value)

func find_by_role(value: int) -> Array[RunnerRunMember]:
	return find_by(&"role", value)

func first_by_role(value: int) -> RunnerRunMember:
	return first_by(&"role", value)

func find_by_damage(value: int) -> Array[RunnerRunMember]:
	return find_by(&"damage", value)

func first_by_damage(value: int) -> RunnerRunMember:
	return first_by(&"damage", value)

func find_by_armor(value: int) -> Array[RunnerRunMember]:
	return find_by(&"armor", value)

func first_by_armor(value: int) -> RunnerRunMember:
	return first_by(&"armor", value)

func find_by_max_hp(value: int) -> Array[RunnerRunMember]:
	return find_by(&"max_hp", value)

func first_by_max_hp(value: int) -> RunnerRunMember:
	return first_by(&"max_hp", value)

func find_by_dodge_charges(value: int) -> Array[RunnerRunMember]:
	return find_by(&"dodge_charges", value)

func first_by_dodge_charges(value: int) -> RunnerRunMember:
	return first_by(&"dodge_charges", value)

func find_by_loot(value: int) -> Array[RunnerRunMember]:
	return find_by(&"loot", value)

func first_by_loot(value: int) -> RunnerRunMember:
	return first_by(&"loot", value)

func find_by_extracted(value: bool) -> Array[RunnerRunMember]:
	return find_by(&"extracted", value)

func first_by_extracted(value: bool) -> RunnerRunMember:
	return first_by(&"extracted", value)

func find_by_died(value: bool) -> Array[RunnerRunMember]:
	return find_by(&"died", value)

func first_by_died(value: bool) -> RunnerRunMember:
	return first_by(&"died", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as RunnerRunMember)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as RunnerRunMember, new_row as RunnerRunMember)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as RunnerRunMember)
