# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerPartyMemberTable extends _ModuleTable

signal inserted(row: RunnerPartyMember)
signal updated(old_row: RunnerPartyMember, new_row: RunnerPartyMember)
signal deleted(row: RunnerPartyMember)

var id: RunnerPartyMemberIdUniqueIndex
var identity: RunnerPartyMemberIdentityUniqueIndex
var party_id: RunnerPartyMemberPartyIdBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"party_member"
	id = RunnerPartyMemberIdUniqueIndex.new(p_local_db)
	identity = RunnerPartyMemberIdentityUniqueIndex.new(p_local_db)
	party_id = RunnerPartyMemberPartyIdBTreeIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[RunnerPartyMember]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[RunnerPartyMember] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[RunnerPartyMember]:
	var rows: Array = super(predicate)
	var typed_array: Array[RunnerPartyMember] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> RunnerPartyMember:
	return super(predicate) as RunnerPartyMember

func find_by(field: StringName, value: Variant) -> Array[RunnerPartyMember]:
	var rows: Array = super(field, value)
	var typed_array: Array[RunnerPartyMember] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> RunnerPartyMember:
	return super(field, value) as RunnerPartyMember

func find_by_id(value: int) -> Array[RunnerPartyMember]:
	var row: RunnerPartyMember = id.find(value)
	var result: Array[RunnerPartyMember] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> RunnerPartyMember:
	return id.find(value)

func find_by_party_id(value: int) -> Array[RunnerPartyMember]:
	return party_id.filter(value)

func first_by_party_id(value: int) -> RunnerPartyMember:
	return party_id._first_row(value) as RunnerPartyMember

func find_by_identity(value: PackedByteArray) -> Array[RunnerPartyMember]:
	var row: RunnerPartyMember = identity.find(value)
	var result: Array[RunnerPartyMember] = []
	if row != null:
		result.append(row)
	return result

func first_by_identity(value: PackedByteArray) -> RunnerPartyMember:
	return identity.find(value)

func find_by_ready(value: bool) -> Array[RunnerPartyMember]:
	return find_by(&"ready", value)

func first_by_ready(value: bool) -> RunnerPartyMember:
	return first_by(&"ready", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as RunnerPartyMember)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as RunnerPartyMember, new_row as RunnerPartyMember)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as RunnerPartyMember)
