# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerInventoryItemTable extends _ModuleTable

signal inserted(row: RunnerInventoryItem)
signal updated(old_row: RunnerInventoryItem, new_row: RunnerInventoryItem)
signal deleted(row: RunnerInventoryItem)

var id: RunnerInventoryItemIdUniqueIndex
var owner: RunnerInventoryItemOwnerBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"inventory_item"
	id = RunnerInventoryItemIdUniqueIndex.new(p_local_db)
	owner = RunnerInventoryItemOwnerBTreeIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[RunnerInventoryItem]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[RunnerInventoryItem] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[RunnerInventoryItem]:
	var rows: Array = super(predicate)
	var typed_array: Array[RunnerInventoryItem] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> RunnerInventoryItem:
	return super(predicate) as RunnerInventoryItem

func find_by(field: StringName, value: Variant) -> Array[RunnerInventoryItem]:
	var rows: Array = super(field, value)
	var typed_array: Array[RunnerInventoryItem] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> RunnerInventoryItem:
	return super(field, value) as RunnerInventoryItem

func find_by_id(value: int) -> Array[RunnerInventoryItem]:
	var row: RunnerInventoryItem = id.find(value)
	var result: Array[RunnerInventoryItem] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> RunnerInventoryItem:
	return id.find(value)

func find_by_owner(value: PackedByteArray) -> Array[RunnerInventoryItem]:
	return owner.filter(value)

func first_by_owner(value: PackedByteArray) -> RunnerInventoryItem:
	return owner._first_row(value) as RunnerInventoryItem

func find_by_item_def_id(value: int) -> Array[RunnerInventoryItem]:
	return find_by(&"item_def_id", value)

func first_by_item_def_id(value: int) -> RunnerInventoryItem:
	return first_by(&"item_def_id", value)

func find_by_quantity(value: int) -> Array[RunnerInventoryItem]:
	return find_by(&"quantity", value)

func first_by_quantity(value: int) -> RunnerInventoryItem:
	return first_by(&"quantity", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as RunnerInventoryItem)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as RunnerInventoryItem, new_row as RunnerInventoryItem)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as RunnerInventoryItem)
