# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerEquipmentTable extends _ModuleTable

signal inserted(row: RunnerEquipment)
signal updated(old_row: RunnerEquipment, new_row: RunnerEquipment)
signal deleted(row: RunnerEquipment)

var owner: RunnerEquipmentOwnerUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"equipment"
	owner = RunnerEquipmentOwnerUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[RunnerEquipment]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[RunnerEquipment] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[RunnerEquipment]:
	var rows: Array = super(predicate)
	var typed_array: Array[RunnerEquipment] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> RunnerEquipment:
	return super(predicate) as RunnerEquipment

func find_by(field: StringName, value: Variant) -> Array[RunnerEquipment]:
	var rows: Array = super(field, value)
	var typed_array: Array[RunnerEquipment] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> RunnerEquipment:
	return super(field, value) as RunnerEquipment

func find_by_owner(value: PackedByteArray) -> Array[RunnerEquipment]:
	var row: RunnerEquipment = owner.find(value)
	var result: Array[RunnerEquipment] = []
	if row != null:
		result.append(row)
	return result

func first_by_owner(value: PackedByteArray) -> RunnerEquipment:
	return owner.find(value)

func find_by_weapon_item(value: int) -> Array[RunnerEquipment]:
	return find_by(&"weapon_item", value)

func first_by_weapon_item(value: int) -> RunnerEquipment:
	return first_by(&"weapon_item", value)

func find_by_armor_item(value: int) -> Array[RunnerEquipment]:
	return find_by(&"armor_item", value)

func first_by_armor_item(value: int) -> RunnerEquipment:
	return first_by(&"armor_item", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as RunnerEquipment)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as RunnerEquipment, new_row as RunnerEquipment)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as RunnerEquipment)
