# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerRunServerTable extends _ModuleTable

signal inserted(row: RunnerRunServer)
signal updated(old_row: RunnerRunServer, new_row: RunnerRunServer)
signal deleted(row: RunnerRunServer)

var identity: RunnerRunServerIdentityUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"run_server"
	identity = RunnerRunServerIdentityUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[RunnerRunServer]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[RunnerRunServer] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[RunnerRunServer]:
	var rows: Array = super(predicate)
	var typed_array: Array[RunnerRunServer] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> RunnerRunServer:
	return super(predicate) as RunnerRunServer

func find_by(field: StringName, value: Variant) -> Array[RunnerRunServer]:
	var rows: Array = super(field, value)
	var typed_array: Array[RunnerRunServer] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> RunnerRunServer:
	return super(field, value) as RunnerRunServer

func find_by_identity(value: PackedByteArray) -> Array[RunnerRunServer]:
	var row: RunnerRunServer = identity.find(value)
	var result: Array[RunnerRunServer] = []
	if row != null:
		result.append(row)
	return result

func first_by_identity(value: PackedByteArray) -> RunnerRunServer:
	return identity.find(value)

func find_by_address(value: String) -> Array[RunnerRunServer]:
	return find_by(&"address", value)

func first_by_address(value: String) -> RunnerRunServer:
	return first_by(&"address", value)

func find_by_load(value: int) -> Array[RunnerRunServer]:
	return find_by(&"load", value)

func first_by_load(value: int) -> RunnerRunServer:
	return first_by(&"load", value)

func find_by_last_heartbeat(value: int) -> Array[RunnerRunServer]:
	return find_by(&"last_heartbeat", value)

func first_by_last_heartbeat(value: int) -> RunnerRunServer:
	return first_by(&"last_heartbeat", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as RunnerRunServer)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as RunnerRunServer, new_row as RunnerRunServer)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as RunnerRunServer)
