# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerEquipmentOwnerUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[PackedByteArray, RunnerEquipment] = {}

func _init(p_local_db: LocalDatabase) -> void:
	_table_name = &"equipment"
	_field_name = &"owner"
	_connect_cache_to_db(_cache, p_local_db)

func find(col_val: PackedByteArray) -> RunnerEquipment:
	return _cache.get(col_val, null)
