# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerPlayerTable extends _ModuleTable

signal inserted(row: RunnerPlayer)
signal updated(old_row: RunnerPlayer, new_row: RunnerPlayer)
signal deleted(row: RunnerPlayer)

var identity: RunnerPlayerIdentityUniqueIndex
var party_id: RunnerPlayerPartyIdBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"player"
	identity = RunnerPlayerIdentityUniqueIndex.new(p_local_db)
	party_id = RunnerPlayerPartyIdBTreeIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[RunnerPlayer]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[RunnerPlayer] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[RunnerPlayer]:
	var rows: Array = super(predicate)
	var typed_array: Array[RunnerPlayer] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> RunnerPlayer:
	return super(predicate) as RunnerPlayer

func find_by(field: StringName, value: Variant) -> Array[RunnerPlayer]:
	var rows: Array = super(field, value)
	var typed_array: Array[RunnerPlayer] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> RunnerPlayer:
	return super(field, value) as RunnerPlayer

func find_by_identity(value: PackedByteArray) -> Array[RunnerPlayer]:
	var row: RunnerPlayer = identity.find(value)
	var result: Array[RunnerPlayer] = []
	if row != null:
		result.append(row)
	return result

func first_by_identity(value: PackedByteArray) -> RunnerPlayer:
	return identity.find(value)

func find_by_name(value: String) -> Array[RunnerPlayer]:
	return find_by(&"name", value)

func first_by_name(value: String) -> RunnerPlayer:
	return first_by(&"name", value)

func find_by_role(value: int) -> Array[RunnerPlayer]:
	return find_by(&"role", value)

func first_by_role(value: int) -> RunnerPlayer:
	return first_by(&"role", value)

func find_by_gold(value: int) -> Array[RunnerPlayer]:
	return find_by(&"gold", value)

func first_by_gold(value: int) -> RunnerPlayer:
	return first_by(&"gold", value)

func find_by_online(value: bool) -> Array[RunnerPlayer]:
	return find_by(&"online", value)

func first_by_online(value: bool) -> RunnerPlayer:
	return first_by(&"online", value)

func find_by_party_id(value: int) -> Array[RunnerPlayer]:
	return party_id.filter(value)

func first_by_party_id(value: int) -> RunnerPlayer:
	return party_id._first_row(value) as RunnerPlayer

func find_by_last_seen(value: int) -> Array[RunnerPlayer]:
	return find_by(&"last_seen", value)

func first_by_last_seen(value: int) -> RunnerPlayer:
	return first_by(&"last_seen", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as RunnerPlayer)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as RunnerPlayer, new_row as RunnerPlayer)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as RunnerPlayer)
