# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerItemDefTable extends _ModuleTable

signal inserted(row: RunnerItemDef)
signal updated(old_row: RunnerItemDef, new_row: RunnerItemDef)
signal deleted(row: RunnerItemDef)

var id: RunnerItemDefIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"item_def"
	id = RunnerItemDefIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[RunnerItemDef]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[RunnerItemDef] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[RunnerItemDef]:
	var rows: Array = super(predicate)
	var typed_array: Array[RunnerItemDef] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> RunnerItemDef:
	return super(predicate) as RunnerItemDef

func find_by(field: StringName, value: Variant) -> Array[RunnerItemDef]:
	var rows: Array = super(field, value)
	var typed_array: Array[RunnerItemDef] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> RunnerItemDef:
	return super(field, value) as RunnerItemDef

func find_by_id(value: int) -> Array[RunnerItemDef]:
	var row: RunnerItemDef = id.find(value)
	var result: Array[RunnerItemDef] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> RunnerItemDef:
	return id.find(value)

func find_by_name(value: String) -> Array[RunnerItemDef]:
	return find_by(&"name", value)

func first_by_name(value: String) -> RunnerItemDef:
	return first_by(&"name", value)

func find_by_damage(value: int) -> Array[RunnerItemDef]:
	return find_by(&"damage", value)

func first_by_damage(value: int) -> RunnerItemDef:
	return first_by(&"damage", value)

func find_by_armor(value: int) -> Array[RunnerItemDef]:
	return find_by(&"armor", value)

func first_by_armor(value: int) -> RunnerItemDef:
	return first_by(&"armor", value)

func find_by_hp(value: int) -> Array[RunnerItemDef]:
	return find_by(&"hp", value)

func first_by_hp(value: int) -> RunnerItemDef:
	return first_by(&"hp", value)

func find_by_dodge(value: int) -> Array[RunnerItemDef]:
	return find_by(&"dodge", value)

func first_by_dodge(value: int) -> RunnerItemDef:
	return first_by(&"dodge", value)

func find_by_price(value: int) -> Array[RunnerItemDef]:
	return find_by(&"price", value)

func first_by_price(value: int) -> RunnerItemDef:
	return first_by(&"price", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as RunnerItemDef)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as RunnerItemDef, new_row as RunnerItemDef)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as RunnerItemDef)
