# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerRunTicketTable extends _ModuleTable

signal inserted(row: RunnerRunTicket)
signal updated(old_row: RunnerRunTicket, new_row: RunnerRunTicket)
signal deleted(row: RunnerRunTicket)

var id: RunnerRunTicketIdUniqueIndex
var identity: RunnerRunTicketIdentityBTreeIndex
var run_id: RunnerRunTicketRunIdBTreeIndex
var server: RunnerRunTicketServerBTreeIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"run_ticket"
	id = RunnerRunTicketIdUniqueIndex.new(p_local_db)
	identity = RunnerRunTicketIdentityBTreeIndex.new(p_local_db)
	run_id = RunnerRunTicketRunIdBTreeIndex.new(p_local_db)
	server = RunnerRunTicketServerBTreeIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[RunnerRunTicket]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[RunnerRunTicket] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[RunnerRunTicket]:
	var rows: Array = super(predicate)
	var typed_array: Array[RunnerRunTicket] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> RunnerRunTicket:
	return super(predicate) as RunnerRunTicket

func find_by(field: StringName, value: Variant) -> Array[RunnerRunTicket]:
	var rows: Array = super(field, value)
	var typed_array: Array[RunnerRunTicket] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> RunnerRunTicket:
	return super(field, value) as RunnerRunTicket

func find_by_id(value: int) -> Array[RunnerRunTicket]:
	var row: RunnerRunTicket = id.find(value)
	var result: Array[RunnerRunTicket] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> RunnerRunTicket:
	return id.find(value)

func find_by_run_id(value: int) -> Array[RunnerRunTicket]:
	return run_id.filter(value)

func first_by_run_id(value: int) -> RunnerRunTicket:
	return run_id._first_row(value) as RunnerRunTicket

func find_by_identity(value: PackedByteArray) -> Array[RunnerRunTicket]:
	return identity.filter(value)

func first_by_identity(value: PackedByteArray) -> RunnerRunTicket:
	return identity._first_row(value) as RunnerRunTicket

func find_by_server(value: PackedByteArray) -> Array[RunnerRunTicket]:
	return server.filter(value)

func first_by_server(value: PackedByteArray) -> RunnerRunTicket:
	return server._first_row(value) as RunnerRunTicket

func find_by_secret(value: String) -> Array[RunnerRunTicket]:
	return find_by(&"secret", value)

func first_by_secret(value: String) -> RunnerRunTicket:
	return first_by(&"secret", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as RunnerRunTicket)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as RunnerRunTicket, new_row as RunnerRunTicket)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as RunnerRunTicket)
