# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerPartyTable extends _ModuleTable

signal inserted(row: RunnerParty)
signal updated(old_row: RunnerParty, new_row: RunnerParty)
signal deleted(row: RunnerParty)

var id: RunnerPartyIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	_table_name = &"party"
	id = RunnerPartyIdUniqueIndex.new(p_local_db)
	on_insert(_emit_inserted)
	on_update(_emit_updated)
	on_delete(_emit_deleted)

func iter() -> Array[RunnerParty]:
	var rows: Array[_ModuleTableType] = super()
	var typed_array: Array[RunnerParty] = []
	typed_array.assign(rows)
	return typed_array

func find_where(predicate: Callable) -> Array[RunnerParty]:
	var rows: Array = super(predicate)
	var typed_array: Array[RunnerParty] = []
	typed_array.assign(rows)
	return typed_array

func first_where(predicate: Callable) -> RunnerParty:
	return super(predicate) as RunnerParty

func find_by(field: StringName, value: Variant) -> Array[RunnerParty]:
	var rows: Array = super(field, value)
	var typed_array: Array[RunnerParty] = []
	typed_array.assign(rows)
	return typed_array

func first_by(field: StringName, value: Variant) -> RunnerParty:
	return super(field, value) as RunnerParty

func find_by_id(value: int) -> Array[RunnerParty]:
	var row: RunnerParty = id.find(value)
	var result: Array[RunnerParty] = []
	if row != null:
		result.append(row)
	return result

func first_by_id(value: int) -> RunnerParty:
	return id.find(value)

func find_by_leader(value: PackedByteArray) -> Array[RunnerParty]:
	return find_by(&"leader", value)

func first_by_leader(value: PackedByteArray) -> RunnerParty:
	return first_by(&"leader", value)

func find_by_zone(value: String) -> Array[RunnerParty]:
	return find_by(&"zone", value)

func first_by_zone(value: String) -> RunnerParty:
	return first_by(&"zone", value)

func find_by_state(value: String) -> Array[RunnerParty]:
	return find_by(&"state", value)

func first_by_state(value: String) -> RunnerParty:
	return first_by(&"state", value)

func _emit_inserted(row: _ModuleTableType) -> void:
	inserted.emit(row as RunnerParty)

func _emit_updated(old_row: _ModuleTableType, new_row: _ModuleTableType) -> void:
	updated.emit(old_row as RunnerParty, new_row as RunnerParty)

func _emit_deleted(row: _ModuleTableType) -> void:
	deleted.emit(row as RunnerParty)
