# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerInventoryItemOwnerBTreeIndex extends _ModuleTableBTreeIndex

var _cache: Dictionary[PackedByteArray, Array] = {}

func _init(p_local_db: LocalDatabase) -> void:
	_table_name = &"inventory_item"
	_field_name = &"owner"
	_connect_cache_to_db(_cache, p_local_db)

func filter(col_val: PackedByteArray) -> Array[RunnerInventoryItem]:
	var typed_array: Array[RunnerInventoryItem] = []
	typed_array.assign(_cache.get(col_val, []))
	return typed_array
