# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name RunnerEquipment extends _ModuleTableType

const module_name : String = "Runner"
const table_names: Array[StringName] = [&'equipment']
const PRIMARY_KEY: StringName = &"owner"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"owner": &"identity", &"weapon_item": &"u64", &"armor_item": &"u64" }

@export var owner: PackedByteArray
@export var weapon_item: int
@export var armor_item: int

## 0. owner: PackedByteArray[br]
## 1. weapon_item: int[br]
## 2. armor_item: int[br]
static func create(p_owner: PackedByteArray, p_weapon_item: int, p_armor_item: int) -> RunnerEquipment:
	var result: RunnerEquipment = RunnerEquipment.new()
	result.owner = p_owner
	result.weapon_item = p_weapon_item
	result.armor_item = p_armor_item
	return result
