# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name RunnerParty extends _ModuleTableType

const module_name : String = "Runner"
const table_names: Array[StringName] = [&'party']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"leader": &"identity", &"zone": &"string", &"state": &"string" }

@export var id: int
@export var leader: PackedByteArray
@export var zone: String
@export var state: String

## 0. id: int[br]
## 1. leader: PackedByteArray[br]
## 2. zone: String[br]
## 3. state: String[br]
static func create(p_id: int, p_leader: PackedByteArray, p_zone: String, p_state: String) -> RunnerParty:
	var result: RunnerParty = RunnerParty.new()
	result.id = p_id
	result.leader = p_leader
	result.zone = p_zone
	result.state = p_state
	return result
