# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name RunnerTrustedServer extends _ModuleTableType

const module_name : String = "Runner"
const table_names: Array[StringName] = []
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"identity": &"identity" }

@export var identity: PackedByteArray

## 0. identity: PackedByteArray[br]
static func create(p_identity: PackedByteArray) -> RunnerTrustedServer:
	var result: RunnerTrustedServer = RunnerTrustedServer.new()
	result.identity = p_identity
	return result
