# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name RunnerRunTicket extends _ModuleTableType

const module_name : String = "Runner"
const table_names: Array[StringName] = [&'run_ticket']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"run_id": &"u64", &"identity": &"identity", &"server": &"identity", &"secret": &"string" }

@export var id: int
@export var run_id: int
@export var identity: PackedByteArray
@export var server: PackedByteArray
@export var secret: String

## 0. id: int[br]
## 1. run_id: int[br]
## 2. identity: PackedByteArray[br]
## 3. server: PackedByteArray[br]
## 4. secret: String[br]
static func create(p_id: int, p_run_id: int, p_identity: PackedByteArray, p_server: PackedByteArray, p_secret: String) -> RunnerRunTicket:
	var result: RunnerRunTicket = RunnerRunTicket.new()
	result.id = p_id
	result.run_id = p_run_id
	result.identity = p_identity
	result.server = p_server
	result.secret = p_secret
	return result
