# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name RunnerPlayer extends _ModuleTableType

const module_name : String = "Runner"
const table_names: Array[StringName] = [&'player']
const PRIMARY_KEY: StringName = &"identity"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"identity": &"identity", &"name": &"string", &"role": &"u8", &"gold": &"u64", &"online": &"bool", &"party_id": &"u64", &"last_seen": &"i64" }

@export var identity: PackedByteArray
@export var name: String
@export var role: int
@export var gold: int
@export var online: bool
@export var party_id: int
@export var last_seen: int

## 0. identity: PackedByteArray[br]
## 1. name: String[br]
## 2. role: int[br]
## 3. gold: int[br]
## 4. online: bool[br]
## 5. party_id: int[br]
## 6. last_seen: int[br]
static func create(p_identity: PackedByteArray, p_name: String, p_role: int, p_gold: int, p_online: bool, p_party_id: int, p_last_seen: int) -> RunnerPlayer:
	var result: RunnerPlayer = RunnerPlayer.new()
	result.identity = p_identity
	result.name = p_name
	result.role = p_role
	result.gold = p_gold
	result.online = p_online
	result.party_id = p_party_id
	result.last_seen = p_last_seen
	return result
