# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name RunnerRunServer extends _ModuleTableType

const module_name : String = "Runner"
const table_names: Array[StringName] = [&'run_server']
const PRIMARY_KEY: StringName = &"identity"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"identity": &"identity", &"address": &"string", &"load": &"u32", &"last_heartbeat": &"i64" }

@export var identity: PackedByteArray
@export var address: String
@export var load: int
@export var last_heartbeat: int

## 0. identity: PackedByteArray[br]
## 1. address: String[br]
## 2. load: int[br]
## 3. last_heartbeat: int[br]
static func create(p_identity: PackedByteArray, p_address: String, p_load: int, p_last_heartbeat: int) -> RunnerRunServer:
	var result: RunnerRunServer = RunnerRunServer.new()
	result.identity = p_identity
	result.address = p_address
	result.load = p_load
	result.last_heartbeat = p_last_heartbeat
	return result
