# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name RunnerRun extends _ModuleTableType

const module_name : String = "Runner"
const table_names: Array[StringName] = [&'run']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"party_id": &"u64", &"zone": &"string", &"seed": &"u64", &"server": &"identity", &"address": &"string", &"state": &"string", &"created_at": &"i64" }

@export var id: int
@export var party_id: int
@export var zone: String
@export var seed: int
@export var server: PackedByteArray
@export var address: String
@export var state: String
@export var created_at: int

## 0. id: int[br]
## 1. party_id: int[br]
## 2. zone: String[br]
## 3. seed: int[br]
## 4. server: PackedByteArray[br]
## 5. address: String[br]
## 6. state: String[br]
## 7. created_at: int[br]
static func create(p_id: int, p_party_id: int, p_zone: String, p_seed: int, p_server: PackedByteArray, p_address: String, p_state: String, p_created_at: int) -> RunnerRun:
	var result: RunnerRun = RunnerRun.new()
	result.id = p_id
	result.party_id = p_party_id
	result.zone = p_zone
	result.seed = p_seed
	result.server = p_server
	result.address = p_address
	result.state = p_state
	result.created_at = p_created_at
	return result
