# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name RunnerPartyMember extends _ModuleTableType

const module_name : String = "Runner"
const table_names: Array[StringName] = [&'party_member']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"party_id": &"u64", &"identity": &"identity", &"ready": &"bool" }

@export var id: int
@export var party_id: int
@export var identity: PackedByteArray
@export var ready: bool

## 0. id: int[br]
## 1. party_id: int[br]
## 2. identity: PackedByteArray[br]
## 3. ready: bool[br]
static func create(p_id: int, p_party_id: int, p_identity: PackedByteArray, p_ready: bool) -> RunnerPartyMember:
	var result: RunnerPartyMember = RunnerPartyMember.new()
	result.id = p_id
	result.party_id = p_party_id
	result.identity = p_identity
	result.ready = p_ready
	return result
