# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name RunnerRunMember extends _ModuleTableType

const module_name : String = "Runner"
const table_names: Array[StringName] = [&'run_member']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"run_id": &"u64", &"identity": &"identity", &"name": &"string", &"role": &"u8", &"damage": &"i32", &"armor": &"i32", &"max_hp": &"i32", &"dodge_charges": &"i32", &"loot": &"i64", &"extracted": &"bool", &"died": &"bool" }

@export var id: int
@export var run_id: int
@export var identity: PackedByteArray
@export var name: String
@export var role: int
@export var damage: int
@export var armor: int
@export var max_hp: int
@export var dodge_charges: int
@export var loot: int
@export var extracted: bool
@export var died: bool

## 0. id: int[br]
## 1. run_id: int[br]
## 2. identity: PackedByteArray[br]
## 3. name: String[br]
## 4. role: int[br]
## 5. damage: int[br]
## 6. armor: int[br]
## 7. max_hp: int[br]
## 8. dodge_charges: int[br]
## 9. loot: int[br]
## 10. extracted: bool[br]
## 11. died: bool[br]
static func create(p_id: int, p_run_id: int, p_identity: PackedByteArray, p_name: String, p_role: int, p_damage: int, p_armor: int, p_max_hp: int, p_dodge_charges: int, p_loot: int, p_extracted: bool, p_died: bool) -> RunnerRunMember:
	var result: RunnerRunMember = RunnerRunMember.new()
	result.id = p_id
	result.run_id = p_run_id
	result.identity = p_identity
	result.name = p_name
	result.role = p_role
	result.damage = p_damage
	result.armor = p_armor
	result.max_hp = p_max_hp
	result.dodge_charges = p_dodge_charges
	result.loot = p_loot
	result.extracted = p_extracted
	result.died = p_died
	return result
