# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name RunnerChatMessage extends _ModuleTableType

const module_name : String = "Runner"
const table_names: Array[StringName] = [&'chat_message']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"channel": &"string", &"sender": &"identity", &"sender_name": &"string", &"text": &"string", &"sent_at": &"i64" }

@export var id: int
@export var channel: String
@export var sender: PackedByteArray
@export var sender_name: String
@export var text: String
@export var sent_at: int

## 0. id: int[br]
## 1. channel: String[br]
## 2. sender: PackedByteArray[br]
## 3. sender_name: String[br]
## 4. text: String[br]
## 5. sent_at: int[br]
static func create(p_id: int, p_channel: String, p_sender: PackedByteArray, p_sender_name: String, p_text: String, p_sent_at: int) -> RunnerChatMessage:
	var result: RunnerChatMessage = RunnerChatMessage.new()
	result.id = p_id
	result.channel = p_channel
	result.sender = p_sender
	result.sender_name = p_sender_name
	result.text = p_text
	result.sent_at = p_sent_at
	return result
