# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name RunnerItemDef extends _ModuleTableType

const module_name : String = "Runner"
const table_names: Array[StringName] = [&'item_def']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"name": &"string", &"slot": &"u8", &"damage": &"i32", &"armor": &"i32", &"hp": &"i32", &"dodge": &"i32", &"price": &"u64" }

@export var id: int
@export var name: String
@export var slot: RunnerTypes.Slot
@export var damage: int
@export var armor: int
@export var hp: int
@export var dodge: int
@export var price: int

## 0. id: int[br]
## 1. name: String[br]
## 2. slot: RunnerTypes.Slot[br]
## 3. damage: int[br]
## 4. armor: int[br]
## 5. hp: int[br]
## 6. dodge: int[br]
## 7. price: int[br]
static func create(p_id: int, p_name: String, p_slot: RunnerTypes.Slot, p_damage: int, p_armor: int, p_hp: int, p_dodge: int, p_price: int) -> RunnerItemDef:
	var result: RunnerItemDef = RunnerItemDef.new()
	result.id = p_id
	result.name = p_name
	result.slot = p_slot
	result.damage = p_damage
	result.armor = p_armor
	result.hp = p_hp
	result.dodge = p_dodge
	result.price = p_price
	return result
