# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name RunnerInventoryItem extends _ModuleTableType

const module_name : String = "Runner"
const table_names: Array[StringName] = [&'inventory_item']
const PRIMARY_KEY: StringName = &"id"
const BSATN_TYPES: Dictionary[StringName, StringName] = { &"id": &"u64", &"owner": &"identity", &"item_def_id": &"u64", &"quantity": &"u32" }

@export var id: int
@export var owner: PackedByteArray
@export var item_def_id: int
@export var quantity: int

## 0. id: int[br]
## 1. owner: PackedByteArray[br]
## 2. item_def_id: int[br]
## 3. quantity: int[br]
static func create(p_id: int, p_owner: PackedByteArray, p_item_def_id: int, p_quantity: int) -> RunnerInventoryItem:
	var result: RunnerInventoryItem = RunnerInventoryItem.new()
	result.id = p_id
	result.owner = p_owner
	result.item_def_id = p_item_def_id
	result.quantity = p_quantity
	return result
