# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerModuleDb extends RefCounted

const table_names : Array[StringName] = [&"chat_message", &"equipment", &"inventory_item", &"item_def", &"party", &"party_member", &"player", &"run", &"run_member", &"run_server", &"run_ticket"]

var chat_message: RunnerChatMessageTable
var equipment: RunnerEquipmentTable
var inventory_item: RunnerInventoryItemTable
var item_def: RunnerItemDefTable
var party: RunnerPartyTable
var party_member: RunnerPartyMemberTable
var player: RunnerPlayerTable
var run: RunnerRunTable
var run_member: RunnerRunMemberTable
var run_server: RunnerRunServerTable
var run_ticket: RunnerRunTicketTable

func _init(p_local_db: LocalDatabase) -> void:
	chat_message = preload('res://spacetime_bindings/schema/tables/runner_chat_message_table.gd').new(p_local_db)
	equipment = preload('res://spacetime_bindings/schema/tables/runner_equipment_table.gd').new(p_local_db)
	inventory_item = preload('res://spacetime_bindings/schema/tables/runner_inventory_item_table.gd').new(p_local_db)
	item_def = preload('res://spacetime_bindings/schema/tables/runner_item_def_table.gd').new(p_local_db)
	party = preload('res://spacetime_bindings/schema/tables/runner_party_table.gd').new(p_local_db)
	party_member = preload('res://spacetime_bindings/schema/tables/runner_party_member_table.gd').new(p_local_db)
	player = preload('res://spacetime_bindings/schema/tables/runner_player_table.gd').new(p_local_db)
	run = preload('res://spacetime_bindings/schema/tables/runner_run_table.gd').new(p_local_db)
	run_member = preload('res://spacetime_bindings/schema/tables/runner_run_member_table.gd').new(p_local_db)
	run_server = preload('res://spacetime_bindings/schema/tables/runner_run_server_table.gd').new(p_local_db)
	run_ticket = preload('res://spacetime_bindings/schema/tables/runner_run_ticket_table.gd').new(p_local_db)
