# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerTypes

const ChatMessage = preload('res://spacetime_bindings/schema/types/runner_chat_message.gd')
const RunResult = preload('res://spacetime_bindings/schema/types/runner_run_result.gd')
const Equipment = preload('res://spacetime_bindings/schema/types/runner_equipment.gd')
const InventoryItem = preload('res://spacetime_bindings/schema/types/runner_inventory_item.gd')
const ItemDef = preload('res://spacetime_bindings/schema/types/runner_item_def.gd')
enum Slot {
	Weapon,
	Armor,
	Potion
}
const Party = preload('res://spacetime_bindings/schema/types/runner_party.gd')
const PartyMember = preload('res://spacetime_bindings/schema/types/runner_party_member.gd')
const Player = preload('res://spacetime_bindings/schema/types/runner_player.gd')
const Run = preload('res://spacetime_bindings/schema/types/runner_run.gd')
const RunMember = preload('res://spacetime_bindings/schema/types/runner_run_member.gd')
const RunServer = preload('res://spacetime_bindings/schema/types/runner_run_server.gd')
const RunTicket = preload('res://spacetime_bindings/schema/types/runner_run_ticket.gd')
