# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name RunnerModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## 0. item_def_id: int [br]
func buy_item(item_def_id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('buy_item', [item_def_id], [&'u64'], &'')

## 0. run_id: int [br]
## 1. results: Array of RunnerRunResult [br]
func commit_run(run_id: int, results: Array[RunnerRunResult]) -> SpacetimeDBReducerCall:
	return _client.call_reducer('commit_run', [run_id, results], [&'u64', &'RunnerRunResult'], &'')

## 0. zone: String [br]
func create_party(zone: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('create_party', [zone], [&'string'], &'')

## 0. inventory_item_id: int [br]
func equip(inventory_item_id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('equip', [inventory_item_id], [&'u64'], &'')

## 0. party_id: int [br]
func join_party(party_id: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('join_party', [party_id], [&'u64'], &'')


func launch_run() -> SpacetimeDBReducerCall:
	return _client.call_reducer('launch_run', [], [], &'')


func leave_party() -> SpacetimeDBReducerCall:
	return _client.call_reducer('leave_party', [], [], &'')

## 0. zone: String [br]
func quick_run(zone: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('quick_run', [zone], [&'string'], &'')

## 0. name: String [br]
func register(name: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('register', [name], [&'string'], &'')

## 0. channel: String [br]
## 1. text: String [br]
func send_chat(channel: String, text: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('send_chat', [channel, text], [&'string', &'string'], &'')

## 0. run_id: int [br]
## 1. address: String [br]
func server_claim_run(run_id: int, address: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('server_claim_run', [run_id, address], [&'u64', &'string'], &'')

## 0. load: int [br]
func server_heartbeat(load: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('server_heartbeat', [load], [&'u32'], &'')

## 0. secret: String [br]
## 1. address: String [br]
func server_register(secret: String, address: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('server_register', [secret, address], [&'string', &'string'], &'')

## 0. zone: String [br]
func set_party_zone(zone: String) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_party_zone', [zone], [&'string'], &'')

## 0. ready: bool [br]
func set_ready(ready: bool) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_ready', [ready], [&'bool'], &'')

## 0. role: int [br]
func set_role(role: int) -> SpacetimeDBReducerCall:
	return _client.call_reducer('set_role', [role], [&'u8'], &'')

