# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name RunnerModuleClient extends SpacetimeDBClient

var reducers: RunnerModuleReducers
var procedures: RunnerModuleProcedures
var db: RunnerModuleDb

func _init() -> void:
	module_name = "Runner"
	name = "RunnerModule"
	reducers = preload('res://spacetime_bindings/schema/module_runner_reducers.gd').new(self)
	procedures = preload('res://spacetime_bindings/schema/module_runner_procedures.gd').new(self)

func _init_db(p_local_db: LocalDatabase) -> void:
	db = preload('res://spacetime_bindings/schema/module_runner_db.gd').new(p_local_db)

## Subscribes to every table in this module with a single handle.
## Mirrors the official SDKs' subscribe-to-all-tables convenience.
func subscribe_all_tables() -> SpacetimeDBSubscription:
	if db == null:
		push_warning('subscribe_all_tables: db not initialized yet')
		return SpacetimeDBSubscription.fail(ERR_UNCONFIGURED)
	var queries: PackedStringArray = []
	for table_name: StringName in db.table_names:
		queries.append('SELECT * FROM %s' % table_name)
	return subscribe(queries)
