# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
extends Node
#SpacetimeDB Autoload

var Runner: RunnerModuleClient

func _init() -> void:
	Runner = preload('res://spacetime_bindings/schema/module_runner_client.gd').new()
	add_child(Runner)
